// <auto-generated />
using System;
using ASC.Core.Common.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASC.Core.Common.Migrations.MSSql.TelegramDbContextMSSql
{
    [DbContext(typeof(MSSqlTelegramDbContext))]
    [Migration("20211025165335_MSSqlTelegramDbContext_Init")]
    partial class MSSqlTelegramDbContext_Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASC.Core.Common.EF.Model.TelegramUser", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("PortalUserId")
                        .HasMaxLength(38)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("portal_user_id");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("int")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("TenantId", "PortalUserId")
                        .HasName("telegram_users_pkey");

                    b.HasIndex("TelegramUserId")
                        .HasDatabaseName("tgId");

                    b.ToTable("telegram_users");
                });
#pragma warning restore 612, 618
        }
    }
}
