// <auto-generated />
using System;
using ASC.Core.Common.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASC.Core.Common.Migrations.MSSql.ResourceDbContextMSSql
{
    [DbContext(typeof(MSSqlResourceDbContext))]
    [Migration("20211025165327_MSSqlResourceDbContext_Init")]
    partial class MSSqlResourceDbContext_Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASC.Core.Common.EF.Model.Resource.ResAuthors", b =>
                {
                    b.Property<string>("Login")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("login")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("isAdmin");

                    b.Property<DateTime>("LastVisit")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastVisit");

                    b.Property<bool>("Online")
                        .HasColumnType("bit")
                        .HasColumnName("online");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.HasKey("Login")
                        .HasName("res_authors_pkey");

                    b.ToTable("res_authors");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.Resource.ResAuthorsFile", b =>
                {
                    b.Property<string>("AuthorLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("authorLogin")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<int>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("fileid");

                    b.Property<bool>("WriteAccess")
                        .HasColumnType("bit")
                        .HasColumnName("writeAccess");

                    b.HasKey("AuthorLogin", "FileId")
                        .HasName("res_authorsfile_pkey");

                    b.HasIndex("FileId")
                        .HasDatabaseName("res_authorsfile_FK2");

                    b.ToTable("res_authorsfile");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.Resource.ResAuthorsLang", b =>
                {
                    b.Property<string>("AuthorLogin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("authorLogin")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("CultureTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cultureTitle")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.HasKey("AuthorLogin", "CultureTitle")
                        .HasName("res_authorslang_pkey");

                    b.HasIndex("CultureTitle")
                        .HasDatabaseName("res_authorslang_FK2");

                    b.ToTable("res_authorslang");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.Resource.ResCultures", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("available");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.HasKey("Title")
                        .HasName("res_cultures_pkey");

                    b.ToTable("res_cultures");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.Resource.ResData", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("fileid");

                    b.Property<string>("CultureTitle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cultureTitle")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("title")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Console")
                        .HasColumnName("authorLogin")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<int>("Flag")
                        .HasColumnType("int")
                        .HasColumnName("flag");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("link")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("resourceType")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("textValue")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<DateTime>("TimeChanges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("timeChanges")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FileId", "CultureTitle", "Title")
                        .HasName("res_data_pkey");

                    b.HasIndex("CultureTitle")
                        .HasDatabaseName("resources_FK2");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("id_res_data");

                    b.HasIndex("TimeChanges")
                        .HasDatabaseName("dateIndex");

                    b.ToTable("res_data");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.Resource.ResFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("'1975-03-03 00:00:00'");

                    b.Property<bool>("IsLock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isLock");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("lastUpdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("moduleName")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("projectName")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("ResName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("resName")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.HasKey("Id");

                    b.HasIndex("ResName")
                        .IsUnique()
                        .HasDatabaseName("resname");

                    b.ToTable("res_files");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.Resource.ResReserve", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("fileid");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("title")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<string>("CultureTitle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cultureTitle")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.Property<int>("Flag")
                        .HasColumnType("int")
                        .HasColumnName("flag");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("textValue")
                        .UseCollation("LATIN1_GENERAL_100_CI_AS_SC_UTF8");

                    b.HasKey("FileId", "Title", "CultureTitle")
                        .HasName("res_reserve_pkey");

                    b.ToTable("res_reserve");
                });
#pragma warning restore 612, 618
        }
    }
}
