name: Check Comments for Non-English Characters

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.java'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.rb'
      - '**/*.go'
      - '**/*.rs'

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }} ${{ github.head_ref }} > changed_files.txt

      - name: Run Comment Checker
        run: |
          EXCLUDE_FILES=("excluded_dir/" "ignore_this_file.py")
          INVALID_FILES=()

          while IFS= read -r file; do
            # Skip excluded files
            for exclude in "${EXCLUDE_FILES[@]}"; do
              [[ "$file" == *"$exclude"* ]] && continue 2
            done

            # Extract comments and check for non-English characters
            if grep -E '^[[:space:]]*([#\/]{1,2}|/\*|\*/)' "$file" | grep -P '[^\x00-\x7F]'; then
              echo "❌ Non-English characters found in comments of $file"
              INVALID_FILES+=("$file")
            fi
          done < changed_files.txt

          if [[ ${#INVALID_FILES[@]} -gt 0 ]]; then
            echo "❌ Non-English characters detected in comments. Fix them before merging."
            exit 1
          else
            echo "✅ All comments are in English."
          fi
